### ISSUE TITLE
My test

### ISSUE THREAD

**Issue by pgl10** [RichardAth/DiophantineSolverMk2#1]
Hello,
I have compiled DiophantineSolverMk2 and I have tried to solve : 
210x^2 - 210y^2 + 464x - 132y - 19571242916  =  0 
But I have got no solutions. In fact, the solution is : x = 10771  y = 4779. 
Do you think my code is not good ? Best regards

**Comment by RichardAth** [comment]
You are right, there was an error. I’ve fixed it and got the following output:

 

Solve Diophantine equation:    210x^2 - 210y^2 + 464x - 132y - 19571242916  =  0

by Dario Alejandro Alpern

x = 10771  y = 4779

 

the change is in function SolveDiscIsSq at line 1558, changed to:

 

      for (long long t1 = 1; t1 <= llSqrt(N1); t1++) {

 

(previously it was

 

               for (unsigned long long t1 = 1; t1 <= llSqrt(N1); t1++) {

 

The error was due to mixing unsigned integers with –ve integers in the same expression.

The master version has been updated.)

**Comment by pgl10** [comment]
Thank you
